// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace GenealogyWebAPI.ClientSdk.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class FamilyProfile
    {
        /// <summary>
        /// Initializes a new instance of the FamilyProfile class.
        /// </summary>
        public FamilyProfile()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FamilyProfile class.
        /// </summary>
        /// <param name="gender">Possible values include: 'Male', 'Female',
        /// 'Unknown'</param>
        public FamilyProfile(string gender, string name = default(string))
        {
            Name = name;
            Gender = gender;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Male', 'Female', 'Unknown'
        /// </summary>
        [JsonProperty(PropertyName = "gender")]
        public string Gender { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Gender == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Gender");
            }
        }
    }
}
